### ISSUE TITLE
Random Output Values at SPI

### ISSUE THREAD

**Issue by ramarya** [whatnick/ATM90E36_Arduino#3]
Hi,
I am using ATM90E36A Development Kit with Nodemcu and tried your Code with following connections
D5-SCK
D6-MISO
D7-MOSI
D3-SS 
(I didn't have adafruit board so tried with above connections on NodeMCU)

and the Output is something like

S0:0x2000
S1:0x6c01
E0:0x7f00
E1:0x2370
VA:2.55V
VB:5.14V
VC:82.54V
IA:0.11A
IB:37.38A
IC:3.65A
f:0.55Hz
S0:0x20ff
S1:0xf002
E0:0xf600
E1:0x3f0
VA:0.01V
VB:350.78V
VC:46.44V
IA:2.82A
IB:3.07A
IC:25.12A
f:4.74Hz
S0:0x6030
S1:0xf100
E0:0x2040
E1:0xf038
VA:9.60V
VB:17.93V
VC:145.90V
IA:0.25A
IB:46.85A
IC:47.37A
f:16.63Hz
S0:0x800f
S1:0x780e
E0:0xe003
E1:0x7f00
VA:10.08V
VB:574.71V
VC:528.64V
IA:65.53A
IB:0.45A
IC:53.12A
f:160.12Hz
S0:0x1bb0
S1:0x6f03
E0:0x11c
E1:0x31
VA:71.04V
VB:291.44V
VC:165.27V
IA:57.36A
IB:33.28A
IC:0.03A
f:5.13Hz

I am not able to trace these random value. 

I also pulled high PM0,PM1, but results are same.

Is it because I didn't calibrated device?
Is there any video or document to calibrate device?

**Comment by whatnick** [comment]
Hi most likely your chip is in DMA mode . Please pull the DMA pin low and the PM0, PM1 pins high.

**Comment by Mshanti113** [comment]
Hii Dhar,
I am working with ESP32 (ESP32 DEVKITV1) to interface ATM90E36 board. However, I got some random value like previous issues (by ramarya) but after pulling DMA pin LOW and PM0 & PM1 HIGH, I'm getting all values 0. 
 Connection:
D5-CS
D18-CLK
D19-MISO
D23-MOSI 


Serial output:
15:44:03.595 -> S0:0xffff
15:44:03.595 -> S1:0xffff
15:44:03.595 -> E0:0xffff
15:44:03.595 -> E1:0xffff
15:44:03.595 -> VA:0.00V
15:44:03.595 -> VB:0.00V
15:44:03.629 -> VC:0.00V
15:44:03.629 -> IA:65.53A
15:44:03.629 -> IB:65.53A
15:44:03.629 -> IC:65.53A
15:44:03.629 -> f: 0.00Hz
15:44:04.649 -> S0:0xffff
15:44:04.649 -> S1:0xffff
15:44:04.649 -> E0:0x0
15:44:04.683 -> E1:0x0
15:44:04.683 -> VA:0.00V
15:44:04.683 -> VB:0.00V
15:44:04.683 -> VC:0.00V
15:44:04.683 -> IA:0.00A
15:44:04.683 -> IB:0.00A
15:44:04.683 -> IC:0.00A
15:44:04.717 -> f: 655.35Hz
15:44:05.703 -> S0:0x0
15:44:05.703 -> S1:0x0
15:44:05.737 -> E0:0x0
15:44:05.737 -> E1:0x0
15:44:05.737 -> VA:655.35V
15:44:05.737 -> VB:655.35V
15:44:05.737 -> VC:655.35V
15:44:05.737 -> IA:0.00A
15:44:05.737 -> IB:0.00A
15:44:05.737 -> IC:0.00A
15:44:05.771 -> f: 655.35Hz
15:44:06.756 -> S0:0x0
15:44:06.790 -> S1:0x0
15:44:06.790 -> E0:0x0
15:44:06.790 -> E1:0x0
15:44:06.790 -> VA:655.35V
15:44:06.790 -> VB:655.35V
15:44:06.790 -> VC:655.35V
15:44:06.824 -> IA:0.00A
15:44:06.824 -> IB:0.00A
15:44:06.824 -> IC:0.00A
15:44:06.824 -> f: 0.00Hz
 
Is it any connection missed ?
Could you tell me what would be the reason ?

Thanks in advance!

**Comment by amarranade** [comment]
> Hi,
> I am using ATM90E36A Development Kit with Nodemcu and tried your Code with following connections
> D5-SCK
> D6-MISO
> D7-MOSI
> D3-SS
> (I didn't have adafruit board so tried with above connections on NodeMCU)
> 
> and the Output is something like
> 
> S0:0x2000
> S1:0x6c01
> E0:0x7f00
> E1:0x2370
> VA:2.55V
> VB:5.14V
> VC:82.54V
> IA:0.11A
> IB:37.38A
> IC:3.65A
> f:0.55Hz
> S0:0x20ff
> S1:0xf002
> E0:0xf600
> E1:0x3f0
> VA:0.01V
> VB:350.78V
> VC:46.44V
> IA:2.82A
> IB:3.07A
> IC:25.12A
> f:4.74Hz
> S0:0x6030
> S1:0xf100
> E0:0x2040
> E1:0xf038
> VA:9.60V
> VB:17.93V
> VC:145.90V
> IA:0.25A
> IB:46.85A
> IC:47.37A
> f:16.63Hz
> S0:0x800f
> S1:0x780e
> E0:0xe003
> E1:0x7f00
> VA:10.08V
> VB:574.71V
> VC:528.64V
> IA:65.53A
> IB:0.45A
> IC:53.12A
> f:160.12Hz
> S0:0x1bb0
> S1:0x6f03
> E0:0x11c
> E1:0x31
> VA:71.04V
> VB:291.44V
> VC:165.27V
> IA:57.36A
> IB:33.28A
> IC:0.03A
> f:5.13Hz
> 
> I am not able to trace these random value.
> 
> I also pulled high PM0,PM1, but results are same.
> 
> Is it because I didn't calibrated device?
> Is there any video or document to calibrate device?

Hey ramarya, just wanted to check with you if you were able to get energy consumption values? If you were able to successfully compute energy, I'd like you to look into the issue I am facing(Getting 0). I've elaborated it under issues section of the same thread. Thanks
