### ISSUE TITLE
How do we  fetch THD and DFT from the chip

### ISSUE THREAD

**Issue by gkankanh** [whatnick/ATM90E36_Arduino#8]
Hi,
Nice Work. Appreciate it. Just wondering about how to fetch DFT and THD from this chip. 
Thanks

**Comment by amarranade** [comment]
> Hi,
> Nice Work. Appreciate it. Just wondering about how to fetch DFT and THD from this chip.
> Thanks

Hey , just wanted to check with you if you were able to get energy consumption values? If you were able to successfully compute energy, I'd like you to look into the issue I am facing(Getting 0). I've elaborated it under issues section of the same thread. Thanks
